version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: shared-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  cart-service:
    image: domi13/cart-service:latest
    container_name: cart-service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: shared-rabbitmq
      RABBITMQ_PORT: 5672
    ports:
      - "5000:5000"

  order-service:
    image: domi13/order-service:latest
    container_name: order-service
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_HOST: shared-rabbitmq
      RABBITMQ_PORT: 5672
    ports:
      - "5001:5001"
